version: "3.9"

services:
  db:
    image: postgres:15
    container_name: suna-postgres
    restart: always
    environment:
      POSTGRES_DB: suna_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: suna-backend
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8000:8001"
    volumes:
      - ./uploads:/app/app/uploads
    restart: always

volumes:
  postgres_data: